### ISSUE TITLE
Link to Figma

### ISSUE THREAD

**Issue by JoepdeJong** [MinBZK/nl-wallet-demo-app#1]
Can a link to the Figma design be shared in this repository?

**Comment by JoepdeJong** [comment]
I found the link already: https://www.figma.com/file/dO5pKIIIyDgG0N2ZX4C2xd/2212_V1_Designs_NL-Voorbeeld-Wallet. Still nice to share it here.

**Comment by HaitskevdLinde** [comment]
Thank you Joep. We will check for an appropriate place to add the link to Figma.
